# Code Generated by Sidekick is for learning and experimentation purposes only.
# streamlit_app.py — Simple form that writes to a OneDrive-synced CSV for Excel

import os
import csv
import threading
from datetime import datetime
from zoneinfo import ZoneInfo
import streamlit as st

# Configure a OneDrive-synced folder path via env var for portability
# Example Windows: setx DATA_DIR "C:\\Users\\you\\OneDrive - OrgName\\form-data"
# Example macOS: export DATA_DIR="$HOME/Library/CloudStorage/OneDrive-OrgName/form-data"
DATA_DIR = os.environ.get("DATA_DIR", "data")
CSV_PATH = os.path.join(DATA_DIR, "submissions.csv")
COLUMNS = ["FullName", "Email", "Lansing", "Role", "SubmittedAt"]
MAX_SUBMISSIONS = 25
# Set as YYYY-MM-DD (America/Detroit).
SURVEY_CLOSE_DATE = os.environ.get("SURVEY_CLOSE_DATE", "2026-04-08")
# Backend override: auto, open, or closed.
SURVEY_STATUS = os.environ.get("SURVEY_STATUS", "closed").strip().lower()
CAPACITY_MESSAGE = (
    "Thank you for your interest! Unfortunately we are at capacity for this in-person session."
)

# Hidden mirror file (same directory; name starts with a dot)
RECENT_FILE = os.path.join(os.path.dirname(DATA_DIR), ".recent_submissions.csv")

os.makedirs(DATA_DIR, exist_ok=True)
_write_lock = threading.Lock()


def get_submission_count():
    if not os.path.exists(CSV_PATH):
        return 0
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        return sum(1 for _ in csv.DictReader(f))


def is_survey_closed(submission_count):
    if SURVEY_STATUS == "open":
        return False
    if SURVEY_STATUS == "closed":
        return True
    if SURVEY_STATUS != "auto":
        st.warning("Invalid SURVEY_STATUS. Use auto, open, or closed.")

    if submission_count >= MAX_SUBMISSIONS:
        return True

    if not SURVEY_CLOSE_DATE:
        return False

    try:
        close_date = datetime.strptime(SURVEY_CLOSE_DATE, "%Y-%m-%d").date()
    except ValueError:
        st.warning("Invalid SURVEY_CLOSE_DATE format. Use YYYY-MM-DD.")
        return False

    today = datetime.now(ZoneInfo("America/Detroit")).date()
    return today >= close_date

def append_row(row_dict):
    is_new = not os.path.exists(CSV_PATH) or os.path.getsize(CSV_PATH) == 0
    with _write_lock:
        with open(CSV_PATH, "a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLUMNS)
            if is_new:
                w.writeheader()
            w.writerow(row_dict)

def append_recent_row(row_dict):
    # Append to hidden mirror file; write header if file is new/empty
    is_new = not os.path.exists(RECENT_FILE) or os.path.getsize(RECENT_FILE) == 0
    with _write_lock:
        with open(RECENT_FILE, "a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLUMNS)
            if is_new:
                w.writeheader()
            # Only write known columns to keep schema stable
            w.writerow({k: row_dict.get(k, "") for k in COLUMNS})

st.set_page_config(page_title="AI First Session 2 Sign-Up", page_icon="📝", layout="centered")
st.title("AI First Session 2 Sign-Up")
st.write("Interested in attending Session 2 of the AI First learning series? Sign up below!")

current_count = get_submission_count()
if is_survey_closed(current_count):
    st.warning(CAPACITY_MESSAGE)
    st.stop()

with st.form("signup", clear_on_submit=True):
    full_name = st.text_input("Full name", placeholder="Jane Doe")
    email = st.text_input("Email", placeholder="jane@example.com")
    role = st.selectbox(
        "Role",
        options=[
            "Developer",
            "Business Analyst",
            "Tester/QA",
            "Project Manager",
            "Design/UX",
            "Leadership/People Manager",
            "Change Management",
            "Other",
        ],
    )
    lansing_choice = st.radio(
        "Will you be co-locating in the Lansing Office on April 14?",
        options=["Yes", "No"],
        horizontal=True
    )
    submitted = st.form_submit_button("Submit")

if submitted:
    # Re-check on submit to avoid accepting entries after close conditions are met.
    latest_count = get_submission_count()
    if is_survey_closed(latest_count):
        st.warning(CAPACITY_MESSAGE)
        st.stop()

    # Minimal validation
    if not full_name.strip():
        st.error("Full name is required.")
        st.stop()
    if "@" not in email or "." not in email:
        st.error("Please provide a valid email address.")
        st.stop()

    row = {
        "FullName": full_name.strip(),
        "Email": email.strip(),
        "Lansing": lansing_choice,  # "Yes" or "No" from the radio
        "Role": role,
        "SubmittedAt": datetime.now(ZoneInfo("America/Detroit")).strftime("%Y-%m-%d %H:%M:%S"),
    }

    try:
        append_row(row)
        append_recent_row(row)  # mirror append to hidden file
        st.success("Thank you! Your submission has been recorded.")
    except Exception as e:
        st.error(f"Could not save your submission: {e}")

st.divider()
st.subheader("Recent submissions")

if os.path.exists(CSV_PATH):
    try:
        with open(CSV_PATH, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        if rows:
            st.dataframe(rows[-25:], use_container_width=True)
        else:
            st.info("No submissions yet.")
    except Exception as e:
        st.warning(f"Unable to load preview: {e}")
else:
    st.info("No submissions yet today.")
