# Code Generated by Sidekick is for learning and experimentation purposes only.
# streamlit_app.py — Simple form that writes to a OneDrive-synced CSV for Excel

import os
import csv
import threading
from datetime import datetime
import streamlit as st

# Configure a OneDrive-synced folder path via env var for portability
# Example Windows: setx DATA_DIR "C:\\Users\\you\\OneDrive - OrgName\\form-data"
# Example macOS: export DATA_DIR="$HOME/Library/CloudStorage/OneDrive-OrgName/form-data"
DATA_DIR = os.environ.get("DATA_DIR", "data")
CSV_PATH = os.path.join(DATA_DIR, "submissions.csv")
COLUMNS = ["FullName", "Email", "Lansing", "SubmittedAt"]

# Hidden mirror file (same directory; name starts with a dot)
RECENT_FILE = os.path.join(os.path.dirname(DATA_DIR), ".recent_submissions.csv")

os.makedirs(DATA_DIR, exist_ok=True)
_write_lock = threading.Lock()

def append_row(row_dict):
    is_new = not os.path.exists(CSV_PATH) or os.path.getsize(CSV_PATH) == 0
    with _write_lock:
        with open(CSV_PATH, "a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLUMNS)
            if is_new:
                w.writeheader()
            w.writerow(row_dict)

def append_recent_row(row_dict):
    # Append to hidden mirror file; write header if file is new/empty
    is_new = not os.path.exists(RECENT_FILE) or os.path.getsize(RECENT_FILE) == 0
    with _write_lock:
        with open(RECENT_FILE, "a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLUMNS)
            if is_new:
                w.writeheader()
            # Only write known columns to keep schema stable
            w.writerow({k: row_dict.get(k, "") for k in COLUMNS})

st.set_page_config(page_title="GenAI Session Sign-Up", page_icon="📝", layout="centered")
st.title("GenAI Session Sign-Up")
st.write("Interested in attending the GenAI in Action: GenAI 101 learning session? Sign up below!")

with st.form("signup", clear_on_submit=True):
    full_name = st.text_input("Full name", placeholder="Jane Doe")
    email = st.text_input("Email", placeholder="jane@example.com")
    lansing_choice = st.radio(
        "Will you be co-locating in the Lansing Office on February 3?",
        options=["Yes", "No"],
        horizontal=True
    )
    submitted = st.form_submit_button("Submit")

if submitted:
    # Minimal validation
    if not full_name.strip():
        st.error("Full name is required.")
        st.stop()
    if "@" not in email or "." not in email:
        st.error("Please provide a valid email address.")
        st.stop()

    row = {
        "FullName": full_name.strip(),
        "Email": email.strip(),
        "Lansing": lansing_choice,  # "Yes" or "No" from the radio
        "SubmittedAt": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
    }

    try:
        append_row(row)
        append_recent_row(row)  # mirror append to hidden file
        st.success("Thank you! Your submission has been recorded.")
    except Exception as e:
        st.error(f"Could not save your submission: {e}")

st.divider()
st.subheader("Recent submissions")

if os.path.exists(CSV_PATH):
    try:
        with open(CSV_PATH, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        if rows:
            st.dataframe(rows[-10:], use_container_width=True)
        else:
            st.info("No submissions yet.")
    except Exception as e:
        st.warning(f"Unable to load preview: {e}")
else:
    st.info("No submissions yet.")
